### ISSUE TITLE
Support for Angular 9

### ISSUE THREAD

**Issue by varun9690** [amitdahan/ngx-filesize#101]
I am seeing the below error and compilation fails, the app is currently using @angular/core": "9.1.0": **NG6001: Cannot declare 'NgxFilesizeModule' in a NgModule as it's not a part of the current compilation.** Can you please help with this?

**Comment by amitdahan** [comment]
Hey thanks! So you're saying any Angular 9 project is blocked from using the package?

Checking! 
In the meanwhile, in case it doesn't reproduce, is the repo this happens in, public? Can I clone & try?

**Comment by varun9690** [comment]
Thanks for looking into it.

Yes, that's right importing the package breaks compilation at least in my case. I am afraid this is a private repo and cannot be cloned, will try to create a sample app and reproduce the issue to test.

**Comment by amitdahan** [comment]
Hmm so you had to use the library differently?

**Comment by vishnu-dev** [comment]
It's just because you installed the library while `ng serve` was running. Restart the server to include the library in the compilation.
