### ISSUE TITLE
Bump dependencies for Angular 9/10

### ISSUE THREAD

**Issue by sebastian-zarzycki-es** [amitdahan/ngx-filesize#190]
The project currently needs tslib@^1.10.0, where newer Angular uses tslib@^2.0.0, so it complains about missing dependencies during npm install.

**Comment by amitdahan** [comment]
Hey! Sorry for the hold-up.

`v2.0.16` is released now and should work.

**Comment by sebastian-zarzycki-es** [comment]
Well, that was fast :)
