### ISSUE TITLE
Metadata version mismatch on Angular 4

### ISSUE THREAD

**Issue by esune** [amitdahan/ngx-filesize#3]
It looks like the project may not be compatible with Angular 4 (and I am guessing 2 as well).

When building the app, I get the following error message:
**ERROR in Metadata version mismatch for module ../node_modules/ngx-filesize/dist/filesize.module.d.ts, found version 4, expected 3**

`ng --version` outputs this (for reference):
* node: 6.12.3
* os: win32 x64
* angular/animations: 4.4.7
* angular/cdk: 2.0.0-beta.12
* angular/common: 4.4.7
* angular/compiler: 4.4.7
* angular/compiler-cli: 4.4.7
* angular/core: 4.4.7
* angular/forms: 4.4.7
* angular/http: 4.4.7
* angular/platform-browser: 4.4.7
* angular/platform-browser-dynamic: 4.4.7
* angular/router: 4.4.7
* angular/cli: 1.2.7

**Comment by amitdahan** [comment]
Hmm, yeah I think I only tested it on 5.X. Thanks for letting me know! I'll see what I can do!
