### ISSUE TITLE
Breaking changes in `filesize`

### ISSUE THREAD

**Issue by undsoft** [amitdahan/ngx-filesize#355]
Version 8.0 of `filesize` significantly alters default behaviour.
https://github.com/avoidwork/filesize.js/blob/master/CHANGELOG.md
https://github.com/avoidwork/filesize.js/pull/138/files

Previously:
```
filesize(265318); // "259.1 KB"
```

Now:
```
filesize(265318); // "265.32 kB"
```

Because ngx-filesize just requires `"filesize": ">= 4.0.0"`, it will silently update to the latest version of filesize regardless of breaking changes now and in the future.
This may introduce hard-to-diagnose issues in the project.

Suggested solutions:
- Move `filesize` to be a peer dependency.
- Or fix `filesize` dependency to a major version and update major number of `ngx-filesize` when there is a major change in `filesize`.

**Comment by amitdahan** [comment]
`3.0.0-alpha.0` is out with `filesize >= 6.0.0 < 10.0.0` as a `peerDep`.

Will close this issue once `3.0.0` is out.
