### ISSUE TITLE
ngx-filesize@1.1.2 requires a peer of @angular/core@>=2.0.0 <7.0.0 but none is installed

### ISSUE THREAD

**Issue by rallets** [amitdahan/ngx-filesize#4]
Hi, I got this warning with Angular 7.0.0
ngx-filesize@1.1.2 requires a peer of @angular/core@>=2.0.0 <7.0.0 but none is installed

There is a specific reason to set the peerDependencies to 2.0.0-7.0.0 in package.json? Can the upper limit be removed?

"peerDependencies": {
    "@angular/core": ">=2.0.0 <7.0.0"
  }

Thank you

**Comment by amitdahan** [comment]
Hey, I'm sorry I haven't been around to maintaining this properly, does it work fine with version 7? I'll accept a PR changing the peer dependency restriction (it was written while 6 was in beta if I recall correctly)

**Comment by jcharra** [comment]
I'm having this problem, too. Are you planning to release a new version with the ng8 version limit soon?

**Comment by amitdahan** [comment]
Fixed, sorry it took me so long!
