### ISSUE TITLE
update peer dependencies for Angular 8

### ISSUE THREAD

**Issue by PaluMacil** [amitdahan/ngx-filesize#6]
on install: ngx-filesize@1.1.3 requires a peer of @angular/core@>=2.0.0 <8.0.0 but none is installed. You must install peer dependencies yourself.

It builds fine, though, so I think a version bump is all you need.

**Comment by amitdahan** [comment]
`1.1.4` is released! Can you check again?

**Comment by amitdahan** [comment]
Closed via #10.
